### ISSUE TITLE
Project still in development? Features? 

### ISSUE THREAD

**Issue by MatthewReed303** [leofds/iot-ladder-editor#2]
How can you add existing Arduino library's/code? Does it compile to complete Arduino code or compile to a library that is added to the ESP32? 

I have other code running on the ESP32 such as webserver etc that I would like to use along the side 

Have the ability to create user defined function blocks with C++ code? This way we can add custom functions like Modbus RTU/TCP do advanced stuff with I2C/SPI or calculations etc

**Comment by leofds** [comment]
This project compiles a complete Arduino code. Custom functions are not supported.
